spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://115.29.173.175:3306/stu_course?setUnicode=true&characterEncoding=utf8&useSSL=false
  thymeleaf:
    encoding: utf-8
    mode: HTML
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
server:
  port: 8080
  servlet:
    context-path: /course
mybatis:
  type-aliases-package: com.studentManager.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      studentmanager:
        mapper: debug
